### ISSUE TITLE
权重百度网盘缺失

### ISSUE THREAD

**Issue by Rofiona** [nowander/WaveNet#1]
您好，您预训练权重的百度网盘链接失效了，可以补充一下吗，谢谢！

**Comment by nowander** [comment]
你好 最新的权重已经上传


| |
孙帆
|
|
***@***.***
|
签名由网易邮箱大师定制
在2023年7月6日 ***@***.***> 写道：

您好，您预训练权重的百度网盘链接失效了，可以补充一下吗，谢谢！
